import * as m from "zigbee-herdsman-converters/lib/modernExtend";

export default {
  zigbeeModel: ["3RPL01084Z"],
  model: "3RPL01084Z",
  vendor: "Third Reality",
  description: "Multi-Function Smart Presence Sensor R3",
  ota: true,
  extend: [
    m.occupancy(),
    m.illuminance(),
    m.deviceAddCustomCluster("3r60gRadarSpecialCluster", {
      name: "3r60gRadarSpecialCluster",
      ID: 0x042e,
      manufacturerCode: 0x1407,
      attributes: {
        totalVolatileOrganicCompounds: {
          name: "totalVolatileOrganicCompounds",
          ID: 0x0000,
          type: 0x39,
          write: false,
          max: 0xffffffff,
        },
        presenceSensorDetectDistanceLevel: {name: "presenceSensorDetectDistanceLevel", ID: 0xF002, type: 0x20, write: true, min: 1, max: 6 },
        tvocSensorCalibration: {name: "tvocSensorCalibration", ID: 0xF001, type: 0x20, write: true, min: 1, max: 1 },
        tvocAlertThreshold: {name: "tvocAlertThreshold", ID: 0xF003, type: 0x21, write: true, min: 3000, max: 50000 },
        motionDetectSensitivityLevel: {name: "motionDetectSensitivityLevel", ID: 0xF004, type: 0x20, write: true, min: 0, max: 20 },
        presenceDetectSensitivityLevel: {name: "presenceDetectSensitivityLevel", ID: 0xF005, type: 0x20, write: true, min: 0, max: 20},
        presenceHoldTimeLevel: {name: "presenceHoldTimeLevel", ID: 0xF006, type: 0x20, write: true, min: 1, max: 4 },
        tvocAlertEnable: {name: "tvocAlertEnable", ID: 0xF007, type: 0x20, write: true, min: 0, max: 1 },
      },
      commands: {},
      commandsResponse: {},
    }),
    m.numeric({
      name: "total_volatile_organic_compounds",
      cluster: "3r60gRadarSpecialCluster",
      attribute: "totalVolatileOrganicCompounds",
      unit: "ppb",
      description: "Measured TVOC value",
      access: "STATE_GET",
    }),
    m.enumLookup({
      name: "tvoc_sensor_calibration",
      lookup: {Reset: 1},
      cluster: "3r60gRadarSpecialCluster",
      attribute: "tvocSensorCalibration",
      description: "TVOC sensor calibration",
      access: "ALL",
    }),
    m.numeric({
      name: "presence_sensor_detect_distance_level",
      valueMin: 1,
      valueMax: 6,
      cluster: "3r60gRadarSpecialCluster",
      attribute: "presenceSensorDetectDistanceLevel",
      description: "Presence detect distance level",
      access: "ALL",
    }),
    m.numeric({
      name: "tvoc_alert_threshold",
      valueMin: 3000,
      valueMax: 50000,
      cluster: "3r60gRadarSpecialCluster",
      attribute: "tvocAlertThreshold",
      unit: "ppb",
      description: "TVOC alert threshold",
      access: "ALL",
    }),
    m.binary({
      name: "tvoc_alert_enable",
      valueOn: ["ON", 1],
      valueOff: ["OFF", 0],
      cluster: "3r60gRadarSpecialCluster",
      attribute: "tvocAlertEnable",
      description: "TVOC alert enable",
      access: "ALL",
    }),
    m.numeric({
      name: "motion_detect_sensitivity_level",
      valueMin: 0,
      valueMax: 20,
      cluster: "3r60gRadarSpecialCluster",
      attribute: "motionDetectSensitivityLevel",
      unit: "level",
      description: "Set motion detect sensitivity level",
      access: "ALL",
    }),
    m.numeric({
      name: "presence_detect_sensitivity_level",
      valueMin: 0,
      valueMax: 20,
      cluster: "3r60gRadarSpecialCluster",
      attribute: "presenceDetectSensitivityLevel",
      unit: "level",
      description: "Set presence sensor sensitivity level",
      access: "ALL",
    }),
    m.numeric({
      name: "presence_hold_time_level",
      valueMin: 1,
      valueMax: 4,
      cluster: "3r60gRadarSpecialCluster",
      attribute: "presenceHoldTimeLevel",
      unit: "level",
      description: "Set presence hold time level",
      access: "ALL",
    }),
    m.light({
      color: { modes: ["xy"], enhancedHue: true },
    }),
  ],
};
