import {Zcl} from 'zigbee-herdsman';
import * as m from 'zigbee-herdsman-converters/lib/modernExtend';

export default {
    zigbeeModel: ['3RSP02064Z','3RSPU01080Z','3RSPE02065Z','3RSP0186Z','3RSPJ0187Z'],
    model: '3RSP02064Z',
    vendor: 'Third Reality',
    description: 'Smart Plug Gen3',
	ota: true,
    whiteLabel: [
		{vendor: 'Third Reality', model: '3RSPU01080Z', description: 'Smart Plug UZ1', fingerprint: [{modelID: '3RSPU01080Z'}]},
        {vendor: 'Third Reality', model: '3RSPE02065Z', description: 'Smart Plug E3', fingerprint: [{modelID: '3RSPE02065Z'}]},
        {vendor: 'Third Reality', model: '3RSP0186Z', description: ' Smart Plug C1', fingerprint: [{modelID: '3RSP0186Z'}]},
        {vendor: 'Third Reality', model: '3RSPJ0187Z', description: 'Smart Plug J1', fingerprint: [{modelID: '3RSPJ0187Z'}]},
	],
	extend: [
		m.onOff(), 
		m.electricityMeter({acFrequency: true, powerFactor: true}),
		m.deviceAddCustomCluster("3rPlugGen3Specialcluster", {
            name: "3rPlugGen3Specialcluster",
            ID: 0xff03,
            manufacturerCode: 0x1407,
            attributes: {
                resetTotalEnergy: {name: "resetTotalEnergy", ID: 0x0000, type: Zcl.DataType.UINT8, write: true, max: 0xff},
                countdownToTurnOff: {name: "countdownToTurnOff", ID: 0x0001, type: Zcl.DataType.UINT16, write: true, max: 0xffff},
                countdownToTurnOn: {name: "countdownToTurnOn", ID: 0x0002, type: Zcl.DataType.UINT16, write: true, max: 0xffff},
                allowBind: {name: "allowBind", ID: 0x0020, type: Zcl.DataType.UINT8, write: true, max: 0xff},
                powerRiseThreshold: {name: "powerRiseThreshold", ID: 0x0040, type: Zcl.DataType.UINT16, write: true, min: 0x01, max: 0xc80},
                powerDropThreshold: {name: "powerDropThreshold", ID: 0x0041, type: Zcl.DataType.UINT16, write: true, min: 0x01, max: 0xc80},
                meteringOnlyMode: {name: "meteringOnlyMode", ID: 0x0050, type: Zcl.DataType.UINT8, write: true, max: 0xff},
            },
            commands: {},
            commandsResponse: {},
        }),
        m.deviceAddCustomCluster("genBasic", {
            name: "genBasic",
            ID: Zcl.Clusters.genBasic.ID,
            attributes: {
                ledBrightness: {name: "ledBrightness", ID: 0xFF01, type: Zcl.DataType.UINT8, write: true, max: 0x64},
            },
            commands: {},
            commandsResponse: {},
        }),
        m.numeric({
            name: "led_brightness",
            unit: "%",
            valueMin: 0,
            valueMax: 100,
            cluster: "genBasic",
            attribute: "ledBrightness",
            description: "Set the brightness of LED",
            access: "ALL",
        }),
        m.enumLookup({
            name: "reset_total_energy",
            lookup: {Reset: 1},
            cluster: "3rPlugGen3Specialcluster",
            attribute: "resetTotalEnergy",
            description: "Reset the sum of consumed energy",
            access: "ALL",
        }),
        m.binary({
            name: "metering_only_mode",
            valueOn: ["ON", 1],
            valueOff: ["OFF", 0],
            cluster: "3rPlugGen3Specialcluster",
            attribute: "meteringOnlyMode",
            description: "When enabled, the device enters metering-only mode and the relay is forced to stay ON.",
            access: "ALL",
        }),
        m.numeric({
            name: "countdown_to_turn_off",
            unit: "s",
            valueMin: 0,
            valueMax: 65535,
            cluster: "3rPlugGen3Specialcluster",
            attribute: "countdownToTurnOff",
            description: "(ON-OFF)",
            access: "ALL",
        }),
        m.numeric({
            name: "countdown_to_turn_on",
            unit: "s",
            valueMin: 0,
            valueMax: 65535,
            cluster: "3rPlugGen3Specialcluster",
            attribute: "countdownToTurnOn",
            description: "(OFF-ON)",
            access: "ALL",
        }),
        m.numeric({
            name: "power_rise_threshold",
            unit: "w",
            valueMin: 1,
            valueMax: 3200,
            cluster: "3rPlugGen3Specialcluster",
            attribute: "powerRiseThreshold",
            description: "Reports sudden power changes. Power rise and fall alerts can be enabled separately. Threshold adjustable.",
            access: "ALL",
        }),
        m.numeric({
            name: "power_drop_threshold",
            unit: "w",
            valueMin: 1,
            valueMax: 3200,
            cluster: "3rPlugGen3Specialcluster",
            attribute: "powerDropThreshold",
            description: "Reports sudden power changes. Power rise and drop alerts can be enabled separately. Threshold adjustable.",
            access: "ALL",
        }),
		],
};