import * as m from 'zigbee-herdsman-converters/lib/modernExtend';

export default {
    zigbeeModel: ['3RTHS0324Z'],
    model: '3RTHS0324Z',
    vendor: 'Third Reality, Inc',
    description: 'Temperature and Humidity Sensor Lite Gen2',
    ota: true,
    extend: [
        m.deviceAddCustomCluster("3rSpecialCluster", {
            ID: 0xff01,
            manufacturerCode: 0x1407,
            attributes: {
                celsiusDegreeCalibration: {ID: 0x0031, type: 0x29, write: true, min: -32768},
                humidityCalibration: {ID: 0x0032, type: 0x29, write: true, min: -32768},
                fahrenheitDegreeCalibration: {ID: 0x0033, type: 0x29, write: true, min: -32768},
                test: {ID: 0x00ff, type: 0x29, write: true, min: -32768},
            },
            commands: {},
            commandsResponse: {},
        }),
        m.battery(),
        m.temperature(),
        m.humidity(),
        m.commandsOnOff(),
        m.numeric({
            name: "celsius_degree_calibration",
            unit: "°C",
            valueMin: -200,
            valueMax: 200,
            scale: 100,
            cluster: "3rSpecialCluster",
            attribute: "celsiusDegreeCalibration",
            description: "Celsius degree calibration",
            access: "ALL",
        }),
        m.numeric({
            name: "humidity_calibration",
            unit: "%",
            valueMin: -100,
            valueMax: 100,
            scale: 100,
            cluster: "3rSpecialCluster",
            attribute: "humidityCalibration",
            description: "Humidity calibration",
            access: "ALL",
        }),
        m.numeric({
            name: "fahrenheit_degree_calibration",
            unit: "°F",
            valueMin: -200,
            valueMax: 200,
            scale: 100,
            cluster: "3rSpecialCluster",
            attribute: "fahrenheitDegreeCalibration",
            description: "Fahrenheit degree calibration",
            access: "ALL",
        }),
    ],
};
